In [1]:
import requests

url = "https://api.clickup.com/api/v2/list/901202319556/task?subtasks=true"
headers = {
    "Authorization": "pk_93882701_5X39IECQRBNWFTVZBYSJH5CXKU79HS55"
}

r = requests.get(url, headers=headers)
print(r.status_code)
print(r.json())

200

In [2]:
import pandas as pd
try:
    api_json_data = r.json()

    if isinstance(api_json_data, list):
        df_api = pd.DataFrame(api_json_data)
        print("DataFrame from API list response:")
        print(df_api)
    elif isinstance(api_json_data, dict):
        # Check if the dictionary contains a 'tasks' key and if its value is a list
        if 'tasks' in api_json_data and isinstance(api_json_data['tasks'], list):
            df_api = pd.DataFrame(api_json_data['tasks'])
            print("DataFrame from API 'tasks' list within dictionary response:")
            print(df_api)
        else:
            # If it's a dictionary but not with a 'tasks' key, or 'tasks' isn't a list
            # Assume it's a single record or an error message and try to convert as is
            df_api = pd.DataFrame([api_json_data])
            print("DataFrame from API dictionary response (single record or error):")
            print(df_api)
    else:
        print("API response is not a recognized JSON format (list or dict) for DataFrame conversion.")
except NameError:
    print("Error: 'r' (the response object from the API call) is not defined in this scope. Please ensure the API call in the previous cell has been executed successfully and 'r' is available, or re-run it.")
except Exception as e:
    print(f"An error occurred during API JSON processing: {e}")

DataFrame from API 'tasks' list within dictionary response:
           id custom_id  custom_item_id  \
0   869btbuwk      None               0
1   869ahmf7u      None               0
2   869ahmcqj      None               0
3   869agp147      None               0
4   869agp0uz      None               0
5   869af83h1      None               0
6   869af83c0      None               0
7   869af829t      None               0
8   869af7qma      None               0
9   869af7nme      None               0
10  869ab9g7u      None               0
11  869ab1fx3      None               0
12  869aakx8b      None               0
13  869aak1e3      None               0
14  869aafmh1      None               0
15  8698rmb2r      None               0
16  86979jffy      None               0
17  8695242w4      None               0
18  8694x2b1k      None               0
19  8694ubyqx      None               0
20  8694hx7f1      None               0
21  86949kbqq      None               0
22  86932216u      None               0
23  86932216d      None               0
24  869322154      None               0
25  869322137      None               0
26  86931cr2n      None               0
27  86931cqb9      None               0
28  86931cqa1      None               0
29  86931cq82      None               0
30  86931cq5u      None               0
31  86931cq56      None               0

                                              name  \
0                  SnowPro Advanced: Data Engineer
1       Salesforce Certified Agentforce Specialist
2        Salesforce Certified Mulesoft Developer 1
3                     Snowflake Sales Professional
4           Snowflake Technical Sales Professional
5                         Alteryx Designer Advance
6                            Alteryx Designer Core
7       Salesforce Certified Agentforce Specialist
8                                     SnowPro Core
9    AWS Certified Solutions Architect - Associate
10                   AWS Data Engineer - Associate
11                   AWS Data Engineer - Associate
12       Salesforce Certified Mulesoft Developer 1
13                                      Salesforce
14                   AWS Data Engineer - Associate
15   AWS Certified Solutions Architect - Associate
16                   Alteryx Server Administration
17                                           Other
18                       Alteryx Designer Advanced
19             Clickup Certification Board Changes
20                                    SnowPro Core
21                          AWS Cloud Practitioner
22                Map out study path and resources
23  Map out how long it should take to obtain cert
24                Find out which certs and details
25                                      Data Cloud
26              Investigate learning paths/options
27                Map out study path and resources
28                                         PySpark
29                                         Alteryx
30                                             AWS
31                                       Snowflake

                                         text_content  \
0
1
2
3
4
5
6
7
8   This is the Snowflake Partner courses plus the...
9
10
11
12
13  Hi Mitch,\n\nFor Tableau technical issues -  P...
14
15
16
17
18
19  Hi Sandi\n\nAs discussed, we require the follo...
20
21
22
23
24
25
26
27  The ideal resource is SnowPro Core Exam Prepar...
28
29  1. Compile a Needs Assessment:\n   a. We need ...
30
31

                                          description  \
0
1
2
3
4
5
6
7
8   This is the Snowflake Partner courses plus the...
9
10
11
12
13  Hi Mitch,\n\nFor Tableau technical issues -  P...
14
15
16
17
18
19  Hi Sandi\n\nAs discussed, we require the follo...
20
21
22
23
24
25
26
27  The ideal resource is SnowPro Core Exam Prepar...
28
29  1. Compile a Needs Assessment:\n   a. We need ...
30
31

                                               status  \
0   {'status': 'to do', 'id': 'p90100293020_Qr12E7...
1   {'status': 'in progress', 'id': 'p90100293020_...
2   {'status': 'in progress', 'id': 'p90100293020_...
3   {'status': 'in progress', 'id': 'p90100293020_...
4   {'status': 'in progress', 'id': 'p90100293020_...
5   {'status': 'to do', 'id': 'p90100293020_Qr12E7...
6   {'status': 'in progress', 'id': 'p90100293020_...
7   {'status': 'in progress', 'id': 'p90100293020_...
8   {'status': 'in progress', 'id': 'p90100293020_...
9   {'status': 'in progress', 'id': 'p90100293020_...
10  {'status': 'in progress', 'id': 'p90100293020_...
11  {'status': 'in progress', 'id': 'p90100293020_...
12  {'status': 'in progress', 'id': 'p90100293020_...
13  {'status': 'in progress', 'id': 'p90100293020_...
14  {'status': 'in progress', 'id': 'p90100293020_...
15  {'status': 'in progress', 'id': 'p90100293020_...
16  {'status': 'blocked', 'id': 'p90100293020_xMUt...
17  {'status': 'in progress', 'id': 'p90100293020_...
18  {'status': 'in progress', 'id': 'p90100293020_...
19  {'status': 'to do', 'id': 'p90100293020_Qr12E7...
20  {'status': 'to do', 'id': 'p90100293020_Qr12E7...
21  {'status': 'in progress', 'id': 'p90100293020_...
22  {'status': 'to do', 'id': 'p90100293020_Qr12E7...
23  {'status': 'to do', 'id': 'p90100293020_Qr12E7...
24  {'status': 'to do', 'id': 'p90100293020_Qr12E7...
25  {'status': 'to do', 'id': 'p90100293020_Qr12E7...
26  {'status': 'to do', 'id': 'p90100293020_Qr12E7...
27  {'status': 'in progress', 'id': 'p90100293020_...
28  {'status': 'to do', 'id': 'p90100293020_Qr12E7...
29  {'status': 'in progress', 'id': 'p90100293020_...
30  {'status': 'in progress', 'id': 'p90100293020_...
31  {'status': 'in progress', 'id': 'p90100293020_...

                                    orderindex   date_created   date_updated  \
0   237630806.00000000000000000000000000000000  1768454966454  1770259419370
1   237630487.00000000000000000000000000000000  1758275699805  1758275745774
2   237630485.00000000000000000000000000000000  1758275517967  1758275539242
3   237630484.00000000000000000000000000000000  1758092412744  1760106544048
4   237630483.00000000000000000000000000000000  1758092379261  1758092392611
5   237630470.00000000000000000000000000000000  1757679159810  1768457716475
6   237630469.00000000000000000000000000000000  1757679126298  1768457902345
7   237630468.00000000000000000000000000000000  1757678965648  1761891502534
8   237630464.00000000000000000000000000000000  1757677929105  1761891306521
9   237630463.00000000000000000000000000000000  1757677715553  1759213315623
10  237630419.00000000000000000000000000000000  1756819342460  1756819556281
11  237630416.00000000000000000000000000000000  1756794767131  1756794860435
12  237630414.00000000000000000000000000000000  1756717160137  1756717183202
13  119433589.00000000000000000000000000000000  1756715191771  1758618643859
14  237630402.00000000000000000000000000000000  1756705921113  1756714381592
15  237621688.00000000000000000000000000000000  1744791577183  1756710820709
16  237621175.00000000000000000000000000000000  1735807874594  1737463269180
17  119418964.00000000000000000000000000000000  1720616357407  1720616357407
18   33961000.93750000000000000000000000000000  1719292966837  1760710940786
19  119417679.58739817000000000000000000000000  1718272891175  1718367225341
20  237619743.00000000000000000000000000000000  1715604176853  1731935803462
21  237619526.00000000000000000000000000000000  1712840695988  1756714525762
22   33960919.00000000000000000000000000000000  1699011220752  1715584505210
23   33960916.50000000000000000000000000000000  1699011214690  1715584505210
24   33960916.00000600000000000000000000000000  1699011207008  1715584505210
25  119417683.00027170000000000000000000000000  1699011191644  1756807769716
26   33960900.00000000000000000000000000000000  1698781067133  1715584505210
27   33960875.50000000000000000000000000000000  1698780763279  1715605097680
28  119417682.00019030000000000000000000000000  1698780706270  1718357678121
29  119417686.00046620000000000000000000000000  1698780679977  1760105076592
30  119417684.00033400000000000000000000000000  1698780652189  1760105014615
31  119417685.00042290000000000000000000000000  1698780644161  1760105075082

    ... linked_tasks locations     team_id  \
0   ...           []        []  9005125381
1   ...           []        []  9005125381
2   ...           []        []  9005125381
3   ...           []        []  9005125381
4   ...           []        []  9005125381
5   ...           []        []  9005125381
6   ...           []        []  9005125381
7   ...           []        []  9005125381
8   ...           []        []  9005125381
9   ...           []        []  9005125381
10  ...           []        []  9005125381
11  ...           []        []  9005125381
12  ...           []        []  9005125381
13  ...           []        []  9005125381
14  ...           []        []  9005125381
15  ...           []        []  9005125381
16  ...           []        []  9005125381
17  ...           []        []  9005125381
18  ...           []        []  9005125381
19  ...           []        []  9005125381
20  ...           []        []  9005125381
21  ...           []        []  9005125381
22  ...           []        []  9005125381
23  ...           []        []  9005125381
24  ...           []        []  9005125381
25  ...           []        []  9005125381
26  ...           []        []  9005125381
27  ...           []        []  9005125381
28  ...           []        []  9005125381
29  ...           []        []  9005125381
30  ...           []        []  9005125381
31  ...           []        []  9005125381

                                    url  \
0   https://app.clickup.com/t/869btbuwk
1   https://app.clickup.com/t/869ahmf7u
2   https://app.clickup.com/t/869ahmcqj
3   https://app.clickup.com/t/869agp147
4   https://app.clickup.com/t/869agp0uz
5   https://app.clickup.com/t/869af83h1
6   https://app.clickup.com/t/869af83c0
7   https://app.clickup.com/t/869af829t
8   https://app.clickup.com/t/869af7qma
9   https://app.clickup.com/t/869af7nme
10  https://app.clickup.com/t/869ab9g7u
11  https://app.clickup.com/t/869ab1fx3
12  https://app.clickup.com/t/869aakx8b
13  https://app.clickup.com/t/869aak1e3
14  https://app.clickup.com/t/869aafmh1
15  https://app.clickup.com/t/8698rmb2r
16  https://app.clickup.com/t/86979jffy
17  https://app.clickup.com/t/8695242w4
18  https://app.clickup.com/t/8694x2b1k
19  https://app.clickup.com/t/8694ubyqx
20  https://app.clickup.com/t/8694hx7f1
21  https://app.clickup.com/t/86949kbqq
22  https://app.clickup.com/t/86932216u
23  https://app.clickup.com/t/86932216d
24  https://app.clickup.com/t/869322154
25  https://app.clickup.com/t/869322137
26  https://app.clickup.com/t/86931cr2n
27  https://app.clickup.com/t/86931cqb9
28  https://app.clickup.com/t/86931cqa1
29  https://app.clickup.com/t/86931cq82
30  https://app.clickup.com/t/86931cq5u
31  https://app.clickup.com/t/86931cq56

                                              sharing permission_level  \
0   {'public': False, 'public_share_expires_on': N...           create
1   {'public': False, 'public_share_expires_on': N...           create
2   {'public': False, 'public_share_expires_on': N...           create
3   {'public': False, 'public_share_expires_on': N...           create
4   {'public': False, 'public_share_expires_on': N...           create
5   {'public': False, 'public_share_expires_on': N...           create
6   {'public': False, 'public_share_expires_on': N...           create
7   {'public': False, 'public_share_expires_on': N...           create
8   {'public': False, 'public_share_expires_on': N...           create
9   {'public': False, 'public_share_expires_on': N...           create
10  {'public': False, 'public_share_expires_on': N...           create
11  {'public': False, 'public_share_expires_on': N...           create
12  {'public': False, 'public_share_expires_on': N...           create
13  {'public': False, 'public_share_expires_on': N...           create
14  {'public': False, 'public_share_expires_on': N...           create
15  {'public': False, 'public_share_expires_on': N...           create
16  {'public': False, 'public_share_expires_on': N...           create
17  {'public': False, 'public_share_expires_on': N...           create
18  {'public': False, 'public_share_expires_on': N...           create
19  {'public': False, 'public_share_expires_on': N...           create
20  {'public': False, 'public_share_expires_on': N...           create
21  {'public': False, 'public_share_expires_on': N...           create
22  {'public': False, 'public_share_expires_on': N...           create
23  {'public': False, 'public_share_expires_on': N...           create
24  {'public': False, 'public_share_expires_on': N...           create
25  {'public': False, 'public_share_expires_on': N...           create
26  {'public': False, 'public_share_expires_on': N...           create
27  {'public': False, 'public_share_expires_on': N...           create
28  {'public': False, 'public_share_expires_on': N...           create
29  {'public': False, 'public_share_expires_on': N...           create
30  {'public': False, 'public_share_expires_on': N...           create
31  {'public': False, 'public_share_expires_on': N...           create

                                                 list  \
0   {'id': '901202319556', 'name': 'Certification'...
1   {'id': '901202319556', 'name': 'Certification'...
2   {'id': '901202319556', 'name': 'Certification'...
3   {'id': '901202319556', 'name': 'Certification'...
4   {'id': '901202319556', 'name': 'Certification'...
5   {'id': '901202319556', 'name': 'Certification'...
6   {'id': '901202319556', 'name': 'Certification'...
7   {'id': '901202319556', 'name': 'Certification'...
8   {'id': '901202319556', 'name': 'Certification'...
9   {'id': '901202319556', 'name': 'Certification'...
10  {'id': '901202319556', 'name': 'Certification'...
11  {'id': '901202319556', 'name': 'Certification'...
12  {'id': '901202319556', 'name': 'Certification'...
13  {'id': '901202319556', 'name': 'Certification'...
14  {'id': '901202319556', 'name': 'Certification'...
15  {'id': '901202319556', 'name': 'Certification'...
16  {'id': '901202319556', 'name': 'Certification'...
17  {'id': '901202319556', 'name': 'Certification'...
18  {'id': '901202319556', 'name': 'Certification'...
19  {'id': '901202319556', 'name': 'Certification'...
20  {'id': '901202319556', 'name': 'Certification'...
21  {'id': '901202319556', 'name': 'Certification'...
22  {'id': '901202319556', 'name': 'Certification'...
23  {'id': '901202319556', 'name': 'Certification'...
24  {'id': '901202319556', 'name': 'Certification'...
25  {'id': '901202319556', 'name': 'Certification'...
26  {'id': '901202319556', 'name': 'Certification'...
27  {'id': '901202319556', 'name': 'Certification'...
28  {'id': '901202319556', 'name': 'Certification'...
29  {'id': '901202319556', 'name': 'Certification'...
30  {'id': '901202319556', 'name': 'Certification'...
31  {'id': '901202319556', 'name': 'Certification'...

                                              project  \
0   {'id': '90121335991', 'name': 'hidden', 'hidde...
1   {'id': '90121335991', 'name': 'hidden', 'hidde...
2   {'id': '90121335991', 'name': 'hidden', 'hidde...
3   {'id': '90121335991', 'name': 'hidden', 'hidde...
4   {'id': '90121335991', 'name': 'hidden', 'hidde...
5   {'id': '90121335991', 'name': 'hidden', 'hidde...
6   {'id': '90121335991', 'name': 'hidden', 'hidde...
7   {'id': '90121335991', 'name': 'hidden', 'hidde...
8   {'id': '90121335991', 'name': 'hidden', 'hidde...
9   {'id': '90121335991', 'name': 'hidden', 'hidde...
10  {'id': '90121335991', 'name': 'hidden', 'hidde...
11  {'id': '90121335991', 'name': 'hidden', 'hidde...
12  {'id': '90121335991', 'name': 'hidden', 'hidde...
13  {'id': '90121335991', 'name': 'hidden', 'hidde...
14  {'id': '90121335991', 'name': 'hidden', 'hidde...
15  {'id': '90121335991', 'name': 'hidden', 'hidde...
16  {'id': '90121335991', 'name': 'hidden', 'hidde...
17  {'id': '90121335991', 'name': 'hidden', 'hidde...
18  {'id': '90121335991', 'name': 'hidden', 'hidde...
19  {'id': '90121335991', 'name': 'hidden', 'hidde...
20  {'id': '90121335991', 'name': 'hidden', 'hidde...
21  {'id': '90121335991', 'name': 'hidden', 'hidde...
22  {'id': '90121335991', 'name': 'hidden', 'hidde...
23  {'id': '90121335991', 'name': 'hidden', 'hidde...
24  {'id': '90121335991', 'name': 'hidden', 'hidde...
25  {'id': '90121335991', 'name': 'hidden', 'hidde...
26  {'id': '90121335991', 'name': 'hidden', 'hidde...
27  {'id': '90121335991', 'name': 'hidden', 'hidde...
28  {'id': '90121335991', 'name': 'hidden', 'hidde...
29  {'id': '90121335991', 'name': 'hidden', 'hidde...
30  {'id': '90121335991', 'name': 'hidden', 'hidde...
31  {'id': '90121335991', 'name': 'hidden', 'hidde...

                                               folder                  space
0   {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
1   {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
2   {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
3   {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
4   {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
5   {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
6   {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
7   {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
8   {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
9   {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
10  {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
11  {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
12  {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
13  {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
14  {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
15  {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
16  {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
17  {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
18  {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
19  {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
20  {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
21  {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
22  {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
23  {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
24  {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
25  {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
26  {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
27  {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
28  {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
29  {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
30  {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}
31  {'id': '90121335991', 'name': 'hidden', 'hidde...  {'id': '90100293020'}

[32 rows x 39 columns]

In [3]:
df_api['custom_fields']

0     [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
1     [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
2     [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
3     [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
4     [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
5     [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
6     [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
7     [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
8     [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
9     [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
10    [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
11    [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
12    [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
13    [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
14    [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
15    [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
16    [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
17    [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
18    [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
19    [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
20    [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
21    [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
22    [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
23    [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
24    [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
25    [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
26    [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
27    [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
28    [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
29    [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
30    [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
31    [{'id': '0bf35fbd-1f77-4add-b258-62eeb2b1fe8e'...
Name: custom_fields, dtype: object

In [16]:
import pandas as pd
import ast

# 1. Make a copy
df = df_api.copy()

# 2. If custom_fields is stored as text instead of real Python objects, convert it
def parse_if_string(x):
    if isinstance(x, str):
        try:
            return ast.literal_eval(x)
        except:
            return x
    return x

df["custom_fields"] = df["custom_fields"].apply(parse_if_string)

# 3. Recursive function to flatten dictionaries
def flatten_dict(d, parent_key="", sep="_"):
    items = {}
    if not isinstance(d, dict):
        return items

    for k, v in d.items():
        new_key = f"{parent_key}{sep}{k}" if parent_key else str(k)

        if isinstance(v, dict):
            items.update(flatten_dict(v, new_key, sep=sep))
        else:
            items[new_key] = v

    return items

# 4. Flatten each row's custom_fields list into columns
def flatten_custom_fields(custom_fields):
    row_out = {}

    if not isinstance(custom_fields, list):
        return row_out

    for i, field in enumerate(custom_fields):
        if isinstance(field, dict):
            flat_field = flatten_dict(field, parent_key=f"custom_fields_{i}")
            row_out.update(flat_field)

    return row_out

# 5. Apply row by row
custom_fields_expanded = df["custom_fields"].apply(flatten_custom_fields)

# 6. Convert to dataframe
custom_fields_df = pd.DataFrame(custom_fields_expanded.tolist())

# 7. Join back to original dataframe
df_final = pd.concat([df.drop(columns=["custom_fields"]), custom_fields_df], axis=1)

# View result
print(df_final.head())
print(df_final.columns.tolist())

          id custom_id  custom_item_id  \
0  869btbuwk      None               0
1  869ahmf7u      None               0
2  869ahmcqj      None               0
3  869agp147      None               0
4  869agp0uz      None               0

                                         name text_content description  \
0             SnowPro Advanced: Data Engineer
1  Salesforce Certified Agentforce Specialist
2   Salesforce Certified Mulesoft Developer 1
3                Snowflake Sales Professional
4      Snowflake Technical Sales Professional

                                              status  \
0  {'status': 'to do', 'id': 'p90100293020_Qr12E7...
1  {'status': 'in progress', 'id': 'p90100293020_...
2  {'status': 'in progress', 'id': 'p90100293020_...
3  {'status': 'in progress', 'id': 'p90100293020_...
4  {'status': 'in progress', 'id': 'p90100293020_...

                                   orderindex   date_created   date_updated  \
0  237630806.00000000000000000000000000000000  1768454966454  1770259419370
1  237630487.00000000000000000000000000000000  1758275699805  1758275745774
2  237630485.00000000000000000000000000000000  1758275517967  1758275539242
3  237630484.00000000000000000000000000000000  1758092412744  1760106544048
4  237630483.00000000000000000000000000000000  1758092379261  1758092392611

   ... custom_fields_0_value_current custom_fields_0_value_percent_completed  \
0  ...                             0                                     0.0
1  ...                             0                                     0.0
2  ...                             0                                     0.0
3  ...                             0                                     0.0
4  ...                             0                                     0.0

   custom_fields_0_required                    custom_fields_1_id  \
0                     False  5391a196-5257-4828-8015-8b4d31bc6e9d
1                     False  5391a196-5257-4828-8015-8b4d31bc6e9d
2                     False  5391a196-5257-4828-8015-8b4d31bc6e9d
3                     False  5391a196-5257-4828-8015-8b4d31bc6e9d
4                     False  5391a196-5257-4828-8015-8b4d31bc6e9d

  custom_fields_1_name custom_fields_1_type custom_fields_1_date_created  \
0      Expiration Date                 date                1719928804380
1      Expiration Date                 date                1719928804380
2      Expiration Date                 date                1719928804380
3      Expiration Date                 date                1719928804380
4      Expiration Date                 date                1719928804380

  custom_fields_1_hide_from_guests custom_fields_1_required  \
0                            False                    False
1                            False                    False
2                            False                    False
3                            False                    False
4                            False                    False

  custom_fields_0_value_richtext
0                            NaN
1                            NaN
2                            NaN
3                            NaN
4                            NaN

[5 rows x 55 columns]
['id', 'custom_id', 'custom_item_id', 'name', 'text_content', 'description', 'status', 'orderindex', 'date_created', 'date_updated', 'date_closed', 'date_done', 'archived', 'creator', 'assignees', 'group_assignees', 'watchers', 'checklists', 'tags', 'parent', 'top_level_parent', 'priority', 'due_date', 'start_date', 'points', 'time_estimate', 'time_spent', 'dependencies', 'linked_tasks', 'locations', 'team_id', 'url', 'sharing', 'permission_level', 'list', 'project', 'folder', 'space', 'custom_fields_0_id', 'custom_fields_0_name', 'custom_fields_0_type', 'custom_fields_0_type_config_end', 'custom_fields_0_type_config_start', 'custom_fields_0_date_created', 'custom_fields_0_hide_from_guests', 'custom_fields_0_value_current', 'custom_fields_0_value_percent_completed', 'custom_fields_0_required', 'custom_fields_1_id', 'custom_fields_1_name', 'custom_fields_1_type', 'custom_fields_1_date_created', 'custom_fields_1_hide_from_guests', 'custom_fields_1_required', 'custom_fields_0_value_richtext']

In [17]:
display(df_final.filter(like='custom_fields_'))

,custom_fields_0_id,custom_fields_0_name,custom_fields_0_type,custom_fields_0_type_config_end,custom_fields_0_type_config_start,custom_fields_0_date_created,custom_fields_0_hide_from_guests,custom_fields_0_value_current,custom_fields_0_value_percent_completed,custom_fields_0_required,custom_fields_1_id,custom_fields_1_name,custom_fields_1_type,custom_fields_1_date_created,custom_fields_1_hide_from_guests,custom_fields_1_required,custom_fields_0_value_richtext
0,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
1,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
2,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
3,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
4,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
5,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
6,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
7,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
8,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
9,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
10,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
11,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
12,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
13,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
14,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
15,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
16,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
17,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
18,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
19,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
20,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
21,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
22,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
23,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
24,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
25,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
26,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
27,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,75,0.75,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
28,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
29,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
30,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN
31,0bf35fbd-1f77-4add-b258-62eeb2b1fe8e,% Complete,manual_progress,100,0,1693407976021,False,0,0.00,False,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False,NaN

In [7]:
df_final["custom_fields_1_date_created",]

0     1719928804380
1     1719928804380
2     1719928804380
3     1719928804380
4     1719928804380
5     1719928804380
6     1719928804380
7     1719928804380
8     1719928804380
9     1719928804380
10    1719928804380
11    1719928804380
12    1719928804380
13    1719928804380
14    1719928804380
15    1719928804380
16    1719928804380
17    1719928804380
18    1719928804380
19    1719928804380
20    1719928804380
21    1719928804380
22    1719928804380
23    1719928804380
24    1719928804380
25    1719928804380
26    1719928804380
27    1719928804380
28    1719928804380
29    1719928804380
30    1719928804380
31    1719928804380
Name: custom_fields_1_date_created, dtype: object

In [8]:
display(df_final.filter(like='custom_fields_1_'))

,custom_fields_1_id,custom_fields_1_name,custom_fields_1_type,custom_fields_1_date_created,custom_fields_1_hide_from_guests,custom_fields_1_required
0,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
1,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
2,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
3,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
4,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
5,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
6,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
7,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
8,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
9,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
10,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
11,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
12,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
13,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
14,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
15,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
16,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
17,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
18,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
19,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
20,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
21,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
22,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
23,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
24,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
25,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
26,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
27,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
28,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
29,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
30,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False
31,5391a196-5257-4828-8015-8b4d31bc6e9d,Expiration Date,date,1719928804380,False,False

In [15]:
print(df_final['custom_fields_1_date_created'].unique())

<DatetimeArray>
['2024-07-02 14:00:04.380000']
Length: 1, dtype: datetime64[ns]

In [12]:
df_final['custom_fields_1_date_created'] = pd.to_datetime(df_final['custom_fields_1_date_created'], unit='ms')
display(df_final[['name', 'custom_fields_1_name', 'custom_fields_1_date_created']].head())
display(df_final[['custom_fields_1_date_created']].info())

,name,custom_fields_1_name,custom_fields_1_date_created
0,SnowPro Advanced: Data Engineer,Expiration Date,2024-07-02 14:00:04.380
1,Salesforce Certified Agentforce Specialist,Expiration Date,2024-07-02 14:00:04.380
2,Salesforce Certified Mulesoft Developer 1,Expiration Date,2024-07-02 14:00:04.380
3,Snowflake Sales Professional,Expiration Date,2024-07-02 14:00:04.380
4,Snowflake Technical Sales Professional,Expiration Date,2024-07-02 14:00:04.380

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   custom_fields_1_date_created  32 non-null     datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 388.0 bytes

None